import { useEffect, useState } from 'react';
import { api } from '../services/api';
import './Extensions.css';

export default function AccountPanel({onChange,onOpen,view='all',defaultExpanded=false}:{onChange:()=>void;onOpen:(id:string)=>void;view?:'all'|'mailboxes'|'account';defaultExpanded?:boolean}) {
  const [user,setUser]=useState<any>(null),[expanded,setExpanded]=useState(defaultExpanded),[mode,setMode]=useState('login');
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [connections,setConnections]=useState<any>(null),[inbox,setInbox]=useState<any[]>([]),[selected,setSelected]=useState(''),[alerts,setAlerts]=useState<any[]>([]),[prefs,setPrefs]=useState<any>({retention_days:30,mask_reports:false});
  async function reload(){const value=await api('/auth/me');setUser(value.user);if(value.user){setConnections(await api('/mailboxes'));setAlerts(await api('/mailboxes/alerts/list'));setPrefs(await api('/auth/preferences'));}}
  useEffect(()=>{void reload().catch(e=>setError(e.message));},[]);
  useEffect(()=>{if(!user)return;const timer=setInterval(()=>{void api('/mailboxes/alerts/list').then(setAlerts).catch(()=>{});},30000);return()=>clearInterval(timer);},[user?.id]);
  async function action(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function authenticate(){await action(async()=>{await api('/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});setPassword('');await reload();onChange();});}
  async function googleLogin(){await action(async()=>{const value=await api('/mailboxes/google-login/connect',{method:'POST'});window.location.assign(value.url);});}
  async function connect(provider:string){await action(async()=>{const value=await api('/mailboxes/'+provider+'/connect',{method:'POST'});window.location.assign(value.url);});}
  return <section className="account-section wrap">
    <div className="account-heading"><div><span className="eyebrow">{view==='mailboxes'?'CONNECTED MAILBOXES':'YOUR RAKSHAK ACCOUNT'}</span><h2>{view==='mailboxes'?'Bring your inbox into focus.':user?'Welcome back.':'Keep your email checks together.'}</h2><p>{user?user.email:'Sign in to save your checks across devices and connect your inbox.'}</p></div><button className="secondary" onClick={()=>setExpanded(!expanded)}>{expanded?'Close':user?'Open controls'+(alerts.filter(a=>!a.read).length?' · '+alerts.filter(a=>!a.read).length:''):'Sign in / Create account'}</button></div>
    {expanded&&<div className="account-body">{error&&<p className="error" role="alert">{error}</p>}
      {!user?<form className="account-form" onSubmit={e=>{e.preventDefault();void authenticate();}}><h3>{mode==='login'?'Sign in':'Create account'}</h3><button type="button" className="google-login" disabled={busy} onClick={()=>void googleLogin()}><span className="google-mark">G</span>Continue with Google</button><div className="account-divider"><span>or use email</span></div><label>Email<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required minLength={12} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/><small>At least 12 characters. Local prototype: email verification and password recovery are not yet available.</small></label><button className="primary" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button><button type="button" className="text-button" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Create an account':'Already registered? Sign in'}</button><p className="muted">Google login requests your basic profile and verified email only. Inbox access is requested separately if you connect Gmail.</p></form>:<>
      {view!=='account'&&<><div className="connection-intro"><h3>Connect an inbox</h3><p>Read-only access. Check the latest messages when you choose, or enable monitoring for high-risk alerts.</p><div className="extension-actions">{['gmail','outlook'].map(p=><button className="secondary" key={p} disabled={busy||!connections?.providers[p]} onClick={()=>void connect(p)}>Connect {p==='gmail'?'Gmail':'Outlook'}{!connections?.providers[p]?' · Setup required':''}</button>)}</div>{connections&&Object.values(connections.providers).some(v=>!v)&&<p className="muted">The site operator must configure the provider’s OAuth app before connection is available.</p>}</div>
      {connections?.mailboxes.map((m:any)=><article className="mailbox-card" key={m.id}><div><h3>{m.provider==='gmail'?'Gmail':'Outlook'}</h3><small>{m.status}{m.checked_at?' · '+new Date(m.checked_at*1000).toLocaleString():''}</small></div><div className="extension-actions"><button disabled={busy} className="primary" onClick={()=>void action(async()=>{await api('/mailboxes/'+m.id+'/check',{method:'POST'});await reload();})}>Check inbox now</button><button disabled={busy} className="secondary" onClick={()=>void action(async()=>{setSelected(m.id);setInbox(await api('/mailboxes/'+m.id+'/messages'));})}>Browse inbox</button><button disabled={busy} className="secondary" onClick={()=>void action(async()=>{await api('/mailboxes/'+m.id+'/monitor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!m.monitoring})});await reload();})}>{m.monitoring?'Stop monitoring':'Enable monitoring'}</button><button disabled={busy} className="text-button" onClick={()=>void action(async()=>{await api('/mailboxes/'+m.id,{method:'DELETE'});setInbox([]);await reload();})}>Disconnect</button></div></article>)}
      {selected&&<div className="mailbox-list"><h3>Latest inbox messages</h3>{inbox.length?inbox.map(m=><div className="mailbox-message" key={m.id}><div><strong>{m.subject}</strong><small>{m.sender} · {m.date}</small></div><button className="secondary" disabled={busy} onClick={()=>void action(async()=>{const result=await api('/mailboxes/'+selected+'/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message_id:m.id})});if(!result.case_id)throw new Error('This imported result was deleted. Upload the original .eml to analyze again.');onChange();onOpen(result.case_id);await reload();})}>{busy?'Working…':'Analyze'}</button></div>):<p>No messages loaded.</p>}</div>}
      <div className="notification-list"><h3>High-risk email alerts</h3><p>Alerts appear here after monitored emails score 71 or higher. No email or SMS messages are sent.</p>{alerts.length?alerts.map(a=><div className="mailbox-message" key={a.id}><div><strong>{a.message}{a.read?'':' · New'}</strong><small>{new Date(a.created*1000).toLocaleString()}</small></div><button className="text-button" onClick={()=>void action(async()=>{await api('/mailboxes/alerts/'+a.id+'/read',{method:'POST'});onOpen(a.case_id);await reload();})}>View result</button></div>):<p className="muted">No alerts yet.</p>}</div></>}
      {view!=='mailboxes'&&<div className="privacy-preferences"><h3>Privacy and retention</h3><label>Keep investigations <select value={prefs.retention_days} onChange={e=>setPrefs({...prefs,retention_days:Number(e.target.value)})}><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option><option value={365}>1 year</option><option value={0}>Until I delete them</option></select></label><label><input type="checkbox" checked={prefs.mask_reports} onChange={e=>setPrefs({...prefs,mask_reports:e.target.checked})}/> Hide email identities and subject in downloaded reports</label><button className="secondary" disabled={busy} onClick={()=>void action(async()=>{setPrefs(await api('/auth/preferences',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(prefs)}));onChange();})}>Save privacy settings</button></div>}
      <button className="secondary" disabled={busy} onClick={()=>void action(async()=>{await api('/auth/logout',{method:'POST'});setUser(null);setConnections(null);setInbox([]);setAlerts([]);onChange();})}>Sign out</button>
      </>}
    </div>}
  </section>;
}
