import { useMemo, useState } from 'react';
import { Search, ArrowDownUp } from 'lucide-react';
const text=(v:any):string=>v===null||v===undefined?'UNKNOWN':typeof v==='object'?JSON.stringify(v):String(v);
export function DataTable({rows,columns}:{rows:any[];columns:{key:string;label:string}[]}){
 const[query,setQuery]=useState(''),[sort,setSort]=useState(columns[0]?.key||''),[descending,setDescending]=useState(false);
 const filtered=useMemo(()=>rows.filter(r=>text(r).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(typeof a[sort]==='number'&&typeof b[sort]==='number'?a[sort]-b[sort]:text(a[sort]).localeCompare(text(b[sort])))*(descending?-1:1)),[rows,query,sort,descending]);
 return <><div className="table-tools"><label className="search-field"><Search size={16}/><input aria-label="Filter evidence" placeholder="Filter evidence…" value={query} onChange={e=>setQuery(e.target.value)}/></label><small>{filtered.length} of {rows.length} records</small></div><div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}><button className="sort-button" onClick={()=>{if(sort===c.key)setDescending(!descending);else{setSort(c.key);setDescending(false);}}}>{c.label}<ArrowDownUp size={11}/></button></th>)}</tr></thead><tbody>{filtered.map((row,i)=><tr key={i}>{columns.map(c=><td key={c.key}>{['risk','status','risk_level'].includes(c.key)?<span className={'pill '+text(row[c.key])}>{text(row[c.key])}</span>:<span className={['value','url','sha256'].includes(c.key)?'mono':''}>{text(row[c.key])}</span>}</td>)}</tr>)}</tbody></table>{!filtered.length&&<div className="empty">{rows.length?'No matching evidence.':'No evidence available for this section.'}</div>}</div></>
}
export function Facts({data}:{data:any}){return <dl className="facts">{Object.entries(data).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{Array.isArray(v)?(v.length?v.map((x,i)=><div key={i}>{typeof x==='object'?<Facts data={x}/>:text(x)}</div>):'None observed'):v&&typeof v==='object'?<Facts data={v}/>:text(v)}</dd></div>)}</dl>}
