import { lazy, Suspense, useEffect, useState } from 'react';
import { Download, Network, Fingerprint, CheckCircle2, MessageSquare, ArrowUpRight } from 'lucide-react';
import { api, headers } from '../services/api';
import { DataTable, Facts } from './DataTable';
import RiskBreakdown from '../charts/RiskBreakdown';
const Graph=lazy(()=>import('../forensic/ForensicGraph'));
const Map=lazy(()=>import('../maps/InfrastructureMap'));
const tabs=['Overview','Rakshak AI','Authentication','URLs','Domains','IPs','Attachments','Threat Intelligence','IOCs','Campaign Intelligence','Forensic Graph','Infrastructure Map'];
export async function downloadReport(id:string){const response=await fetch('/api/investigations/'+id+'/report',{headers:headers()});if(!response.ok)throw new Error('Report could not be generated.');const url=URL.createObjectURL(await response.blob());const link=document.createElement('a');link.href=url;link.download=id+'-forensic-report.pdf';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function ForensicWorkspace({investigation:c,onOpen}:{investigation:any;onOpen:(id:string)=>void}){
 const[tab,setTab]=useState('Overview'),[notice,setNotice]=useState(''),[verdict,setVerdict]=useState('uncertain'),[notes,setNotes]=useState('');
 useEffect(()=>{setTab('Overview');setNotice('');setVerdict('uncertain');setNotes('');let active=true;api('/investigations/'+c.case_id+'/feedback').then(r=>{if(active&&r){setVerdict(r.verdict);setNotes(r.notes);}}).catch(()=>{});return()=>{active=false;};},[c.case_id]);
 const save=async()=>{try{await api('/investigations/'+c.case_id+'/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({verdict,notes})});setNotice('Analyst feedback saved.');}catch(e){setNotice((e as Error).message);}};
 function exportIOCs(){const blob=new Blob([JSON.stringify(c.iocs,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=c.case_id+'-iocs.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="forensic-workspace" id="case-details"><div className="case-header"><div><span className="eyebrow">INVESTIGATION / {c.case_id}</span><h2>{c.subject||'(No subject)'}</h2><p>{c.sender}</p><div className="case-meta"><span className={'pill '+c.risk_level}>{c.risk_level} · {c.risk_score}/100</span><span>Evidence confidence {c.confidence}%</span><span>{new Date(c.created_at).toLocaleString()}</span></div></div><div className="case-actions"><button onClick={()=>downloadReport(c.case_id).catch(e=>setNotice(e.message))}><Download size={16}/> PDF report</button><button onClick={exportIOCs}><Fingerprint size={16}/> Export IOCs</button></div></div>{notice&&<div className="notice" role="status">{notice}</div>}<div className="tabs" role="tablist" aria-label="Investigation sections">{tabs.map(t=><button role="tab" aria-selected={tab===t} key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="card tab-content" role="tabpanel">
 {tab==='Overview'&&<><div className="detail-grid no-margin"><RiskBreakdown investigation={c}/><div><h2>Investigation timeline</h2><ol className="timeline">{c.timeline.map((s:any,i:number)=><li key={i}><CheckCircle2 size={15}/><div><strong>{s.stage}</strong><small>{s.status} · {s.duration_ms} ms</small></div></li>)}</ol></div></div><div className="overview-bottom"><div><h2>Email metadata</h2><Facts data={{from:c.email.from,to:c.email.to,cc:c.email.cc||'None',reply_to:c.email.reply_to||'None',return_path:c.email.return_path||'None',date:c.email.date||'UNKNOWN',message_id:c.email.message_id||'UNKNOWN',email_sha256:c.email_sha256}}/><details className="body-preview"><summary>Read extracted message text</summary><pre>{c.email.body_text}</pre></details></div><div><h2><MessageSquare size={16}/> Analyst feedback</h2><p className="muted small-text">Saved for review. Feedback does not silently retrain the model or change the original result.</p><label className="field-label">Analyst assessment<select value={verdict} onChange={e=>setVerdict(e.target.value)}><option value="uncertain">Needs further investigation</option><option value="malicious">Malicious</option><option value="benign">Benign</option></select></label><label className="field-label">Investigation notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={2000} rows={4} placeholder="Record your assessment and next steps…"/></label><button onClick={()=>void save()}>Save feedback</button></div></div><details className="limitations"><summary>Methodology and limitations</summary><p>{c.confidence_explanation}</p><ul>{c.limitations?.map((l:string)=><li key={l}>{l}</li>)}</ul></details></>}
 {tab==='Rakshak AI'&&<><div className="ai-detail-heading"><div><span className="eyebrow">RAKSHAK AI</span><h3>{c.ai.category}</h3></div><div><strong>{Math.round(c.ai.probability*100)}%</strong><small>Model phishing probability</small></div></div><p>{c.ai.explanation}</p><p className="notice">{c.ai.model_status}</p><p className="muted">Engine: {c.ai.engine}</p>{c.ai.signals.map((s:any)=><article className="signal-evidence" key={s.signal}><h3>{s.signal}</h3>{s.evidence.map((sentence:string,i:number)=><blockquote key={i}>{sentence}</blockquote>)}</article>)}</>}
 {tab==='Authentication'&&<><p className="notice">Uploaded headers are claims. Only independently trusted receiver results influence authentication risk.</p>{Object.entries(c.auth).map(([name,value])=><article className="auth-detail" key={name}><h3>{name}</h3><Facts data={value}/></article>)}<details className="body-preview"><summary>Received header chain</summary><pre>{c.email.received.join('\n\n')||'No Received headers found.'}</pre></details></>}
 {tab==='URLs'&&<><p className="muted">URLs are shown as text and are never opened automatically. Redirects and final destinations are not fetched.</p><DataTable rows={c.urls} columns={[{key:'url',label:'URL'},{key:'domain',label:'Domain'},{key:'signals',label:'Static signals'},{key:'redirect_status',label:'Redirect analysis'}]}/></>}
 {tab==='Domains'&&<><DataTable rows={c.domains} columns={[{key:'domain',label:'Domain'},{key:'lookalike',label:'Resembles'},{key:'similarity',label:'Similarity %'},{key:'age_days',label:'Age / days'},{key:'registrar',label:'Registrar'},{key:'status',label:'DNS status'}]}/>{c.domains.map((d:any)=><details className="data-detail" key={d.domain}><summary>{d.domain} · DNS / RDAP evidence</summary><Facts data={d}/></details>)}</>}
 {tab==='IPs'&&<><h2>Observed infrastructure</h2><DataTable rows={c.ips} columns={[{key:'ip',label:'IP'},{key:'asn',label:'ASN'},{key:'organization',label:'Organization'},{key:'country',label:'Country'},{key:'vpn',label:'VPN'},{key:'proxy',label:'Proxy'},{key:'tor',label:'Tor'}]}/>{c.ips.map((ip:any)=><details className="data-detail" key={ip.ip}><summary>{ip.ip} · source and location evidence</summary><Facts data={ip}/></details>)}</>}
 {tab==='Attachments'&&<><p className="notice">Static inspection only. A risky file type does not establish maliciousness.</p><DataTable rows={c.attachments} columns={[{key:'filename',label:'Attachment'},{key:'mime_type',label:'MIME type'},{key:'size',label:'Bytes'},{key:'sha256',label:'SHA-256'},{key:'signals',label:'Warnings'}]}/></>}
 {tab==='Threat Intelligence'&&<><p className="muted">Provider results retain their source and lookup time. Missing data is never reported as clean.</p><DataTable rows={c.threat_intel} columns={[{key:'provider',label:'Provider'},{key:'indicator',label:'Indicator'},{key:'status',label:'Status'},{key:'configuration',label:'Configuration'},{key:'queried_at',label:'Lookup time'}]}/>{c.threat_intel.filter((r:any)=>r.status==='AVAILABLE'||r.status==='LOOKUP FAILED').map((r:any,i:number)=><details className="data-detail" key={i}><summary>{r.provider} · {r.indicator}</summary><Facts data={r}/></details>)}</>}
 {tab==='IOCs'&&<><p className="notice">Observed indicators are investigation candidates. “Verified” requires a provider reputation finding.</p><DataTable rows={c.iocs} columns={[{key:'type',label:'Type'},{key:'value',label:'Indicator'},{key:'source',label:'Source'},{key:'risk',label:'Risk'},{key:'reason',label:'Reason'},{key:'confidence',label:'Confidence %'}]}/></>}
 {tab==='Campaign Intelligence'&&<><div className="card-title"><h2><Network size={19}/> Rakshak Campaign Intelligence</h2><span className="tiny-tag">CROSS-CASE ANALYSIS</span></div><p className="muted">Matches against the latest 200 stored investigations. Similarity suggests a relationship and is not attribution.</p>{c.campaigns.length?c.campaigns.map((r:any)=><article className="campaign-card" key={r.case_id}><div><span className="eyebrow">{r.relationship}</span><h3>{r.case_id}</h3><p>{r.subject}</p></div><div className="campaign-score">{r.score}<small>correlation / 100</small></div><DataTable rows={r.shared_indicators} columns={[{key:'type',label:'Shared evidence'},{key:'value',label:'Value'}]}/><button onClick={()=>onOpen(r.case_id)}>Open related investigation <ArrowUpRight size={15}/></button></article>):<div className="empty"><Network size={32}/><h3>No strong campaign connection</h3><p>New cases will be compared with saved evidence. Repeated uploads are labeled as duplicates.</p></div>}</>}
 {tab==='Forensic Graph'&&<Suspense fallback={<div className="empty">Loading forensic graph…</div>}><Graph graph={c.graph}/></Suspense>}
 {tab==='Infrastructure Map'&&<Suspense fallback={<div className="empty">Loading infrastructure map…</div>}><Map ips={c.ips}/></Suspense>}
 </div></section>
}
