import { useEffect, useState } from 'react';
import { api } from '../services/api';
export default function ResultActions({caseId}:{caseId:string}){
  const [language,setLanguage]=useState('English'),[summary,setSummary]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [verdict,setVerdict]=useState('uncertain'),[notes,setNotes]=useState(''),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false);
  useEffect(()=>{let active=true;void api('/investigations/'+caseId+'/feedback').then(v=>{if(active&&v){setVerdict(v.verdict);setNotes(v.notes);setSaved(true);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[caseId]);
  async function summarize(){setBusy(true);setError('');try{setSummary(await api('/investigations/'+caseId+'/summary?language='+language,{method:'POST'}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function feedback(){setSaving(true);setSaved(false);setError('');try{await api('/investigations/'+caseId+'/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({verdict,notes})});setSaved(true);}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  return <div className="result-extras">{error&&<p role="alert" className="error">{error}</p>}<details className="evidence-fold action-card gemini-action"><summary><span><b>Gemini AI</b>Explain this result with Gemini</span><strong>AI SUMMARY</strong></summary><div className="fold-content"><p>On request, Google Gemini receives the risk score, finding names, authentication status and attachment count. Sender addresses, message text and attachment contents are excluded. Generated text may contain errors and does not change the score.</p><div className="extension-actions"><label>Summary language <select value={language} onChange={e=>setLanguage(e.target.value)}>{['English','Hindi','Bengali','Tamil','Telugu','Marathi','Gujarati','Kannada','Malayalam','Punjabi'].map(l=><option key={l}>{l}</option>)}</select></label><button className="primary" disabled={busy} onClick={()=>void summarize()}>{busy?'Preparing…':'Generate explanation'}</button></div>{summary&&<div className="ai-summary" role="status"><small>{summary.status}</small><pre>{summary.summary||'Summary unavailable. The Rakshak evidence and report are still available.'}</pre></div>}</div></details><details className="evidence-fold action-card review-action"><summary><span><b>Your feedback</b>Review this result</span><strong>HELP IMPROVE</strong></summary><div className="fold-content"><p>Your feedback is stored for review and evaluation. It does not automatically retrain the model or change the score.</p><label>Your assessment <select value={verdict} onChange={e=>{setVerdict(e.target.value);setSaved(false);}}><option value="malicious">Phishing / malicious</option><option value="benign">Benign</option><option value="uncertain">Uncertain</option></select></label><label className="feedback-label">Evidence or notes<textarea maxLength={2000} rows={3} value={notes} onChange={e=>{setNotes(e.target.value);setSaved(false);}}/></label><button className="secondary" disabled={saving} onClick={()=>void feedback()}>{saving?'Saving…':'Save feedback'}</button>{saved&&<span role="status"> Feedback saved.</span>}</div></details></div>;
}
